server:
  port: 9090
spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/pr?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: IMS
    password: 2222
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
